#!/bin/bash
#SBATCH --job-name=Lartsev
#SBATCH --time=00:15:00
#SBATCH --nodes=1 --cpus-per-task=18
#SBATCH --partition release

if [ -d utils/build/bin ]; then
    echo "utils found!"         
    
    if [ -d build/bin ]; then
        if [ -f $1 ]; then                    
            ./utils/build/bin/get_sphere_direction $1 build/
            mpirun -n 18 --oversubscribe /nethome/student/FS18/FS2-x1/Lartsev/solver/build/bin/graph_builder /nethome/student/FS18/FS2-x1/Lartsev/solver/config/directories_cfg_claster.json
            mpirun -n 18 --oversubscribe /nethome/student/FS18/FS2-x1/Lartsev/solver/build/bin/trace_builder /nethome/student/FS18/FS2-x1/Lartsev/solver/config/directories_cfg_claster.json             
        else
            echo "file sphere direction not found"
        fi
    else
        echo "build not found"
    fi    
else
    echo "utils not found!"     
fi
